[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/curso"
  to = "/app/dashboard.html"
  status = 200

[[redirects]]
  from = "/entrar"
  to = "/app/login.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200
